const languages = {
  Assamese: "asm_Beng",
  Bengali: "ben_Beng",
  Bodo: "brx_Deva",
  Dogri: "doi_Deva",
  English: "en",
  Konkani: "gom_Deva",
  Gujarati: "guj_Gujr",
  Hindi: "hin_Deva",
  Kannada: "kan_Knda",
  "Kashmiri (Arabic)": "kas_Arab",
  "Kashmiri (Devanagari)": "kas_Deva",
  Maithili: "mai_Deva",
  Malayalam: "mal_Mlym",
  "Manipuri (Bengali)": "mni_Beng",
  "Manipuri (Meitei)": "mni_Mtei",
  Marathi: "mar_Deva",
  Nepali: "npi_Deva",
  Odia: "ory_Orya",
  Punjabi: "pan_Guru",
  Sanskrit: "san_Deva",
  Santali: "sat_Olck",
  "Sindhi (Arabic)": "snd_Arab",
  "Sindhi (Devanagari)": "snd_Deva",
  Tamil: "tam_Taml",
  Telugu: "tel_Telu",
  Urdu: "urd_Arab",
};

export default languages;
